import com.excilys.ebi.gatling.core.Predef._
import com.excilys.ebi.gatling.http.Predef._
import com.excilys.ebi.gatling.script.GatlingSimulation

class Simulation extends GatlingSimulation {

	val urlBase = "http://marvin.cservenak.net:8081"

	val httpConf = httpConfig.baseURL(urlBase)


	val headers_44 = Map(
		"Accept" -> "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2",
		"Accept-Encoding" -> "gzip",
		"Host" -> "localhost:8081",
		"Pragma" -> "no-cache",
		"User-Agent" -> "Apache-Maven/3.0.3 (Java 1.6.0_29; Mac OS X 10.7.2)"
	)

	val chain1 = chain.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_44")
			.get("/nexus/content/groups/public/org/apache/maven/maven/2.0.6/maven-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_45")
			.get("/nexus/content/groups/public/org/apache/maven/maven/2.0.6/maven-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_46")
			.get("/nexus/content/groups/public/org/apache/maven/maven-parent/5/maven-parent-5.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_47")
			.get("/nexus/content/groups/public/org/apache/maven/maven-parent/5/maven-parent-5.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_48")
			.get("/nexus/content/groups/public/org/apache/apache/3/apache-3.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_49")
			.get("/nexus/content/groups/public/org/apache/apache/3/apache-3.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_50")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_51")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_52")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/2.0.6/plexus-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_53")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/2.0.6/plexus-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_54")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_55")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/2.0.5/plexus-utils-2.0.5.jar.sha1")
			.headers(headers_44)
		)
		.pause(300, 400, MILLISECONDS)
		.exec(
			http("request_56")
			.get("/nexus/content/groups/public/org/apache/maven/maven-project/2.0.6/maven-project-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_57")
			.get("/nexus/content/groups/public/org/apache/maven/maven-project/2.0.6/maven-project-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_58")
			.get("/nexus/content/groups/public/org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_59")
			.get("/nexus/content/groups/public/org/apache/maven/maven-settings/2.0.6/maven-settings-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_60")
			.get("/nexus/content/groups/public/org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_61")
			.get("/nexus/content/groups/public/org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_62")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/1.4.1/plexus-utils-1.4.1.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_63")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/1.4.1/plexus-utils-1.4.1.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_64")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/1.0.11/plexus-1.0.11.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_65")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/1.0.11/plexus-1.0.11.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_66")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_67")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_68")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-containers/1.0.3/plexus-containers-1.0.3.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_69")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-containers/1.0.3/plexus-containers-1.0.3.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_70")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/1.0.4/plexus-1.0.4.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_71")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/1.0.4/plexus-1.0.4.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_72")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/1.0.4/plexus-utils-1.0.4.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_73")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/1.0.4/plexus-utils-1.0.4.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_74")
			.get("/nexus/content/groups/public/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_75")
			.get("/nexus/content/groups/public/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_76")
			.get("/nexus/content/groups/public/org/apache/maven/maven-profile/2.0.6/maven-profile-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_77")
			.get("/nexus/content/groups/public/org/apache/maven/maven-profile/2.0.6/maven-profile-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		
	val chain2 = chain
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_78")
			.get("/nexus/content/groups/public/org/apache/maven/maven-artifact-manager/2.0.6/maven-artifact-manager-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_79")
			.get("/nexus/content/groups/public/org/apache/maven/maven-artifact-manager/2.0.6/maven-artifact-manager-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_80")
			.get("/nexus/content/groups/public/org/apache/maven/maven-repository-metadata/2.0.6/maven-repository-metadata-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_81")
			.get("/nexus/content/groups/public/org/apache/maven/maven-repository-metadata/2.0.6/maven-repository-metadata-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_82")
			.get("/nexus/content/groups/public/org/apache/maven/maven-artifact/2.0.6/maven-artifact-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_83")
			.get("/nexus/content/groups/public/org/apache/maven/maven-artifact/2.0.6/maven-artifact-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_84")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-registry/2.0.6/maven-plugin-registry-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_85")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-registry/2.0.6/maven-plugin-registry-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_86")
			.get("/nexus/content/groups/public/org/apache/maven/maven-core/2.0.6/maven-core-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_87")
			.get("/nexus/content/groups/public/org/apache/maven/maven-core/2.0.6/maven-core-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_88")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-parameter-documenter/2.0.6/maven-plugin-parameter-documenter-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_89")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-parameter-documenter/2.0.6/maven-plugin-parameter-documenter-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_90")
			.get("/nexus/content/groups/public/org/apache/maven/reporting/maven-reporting-api/2.0.6/maven-reporting-api-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_91")
			.get("/nexus/content/groups/public/org/apache/maven/reporting/maven-reporting-api/2.0.6/maven-reporting-api-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_92")
			.get("/nexus/content/groups/public/org/apache/maven/reporting/maven-reporting/2.0.6/maven-reporting-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_93")
			.get("/nexus/content/groups/public/org/apache/maven/reporting/maven-reporting/2.0.6/maven-reporting-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_94")
			.get("/nexus/content/groups/public/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_95")
			.get("/nexus/content/groups/public/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_96")
			.get("/nexus/content/groups/public/org/apache/maven/doxia/doxia/1.0-alpha-7/doxia-1.0-alpha-7.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_97")
			.get("/nexus/content/groups/public/org/apache/maven/doxia/doxia/1.0-alpha-7/doxia-1.0-alpha-7.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_98")
			.get("/nexus/content/groups/public/org/apache/maven/maven-error-diagnostics/2.0.6/maven-error-diagnostics-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_99")
			.get("/nexus/content/groups/public/org/apache/maven/maven-error-diagnostics/2.0.6/maven-error-diagnostics-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_100")
			.get("/nexus/content/groups/public/commons-cli/commons-cli/1.0/commons-cli-1.0.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_101")
			.get("/nexus/content/groups/public/commons-cli/commons-cli/1.0/commons-cli-1.0.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_102")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-descriptor/2.0.6/maven-plugin-descriptor-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_103")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-descriptor/2.0.6/maven-plugin-descriptor-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_104")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_105")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_106")
			.get("/nexus/content/groups/public/org/apache/maven/maven-monitor/2.0.6/maven-monitor-2.0.6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_107")
			.get("/nexus/content/groups/public/org/apache/maven/maven-monitor/2.0.6/maven-monitor-2.0.6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_108")
			.get("/nexus/content/groups/public/classworlds/classworlds/1.1/classworlds-1.1.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_109")
			.get("/nexus/content/groups/public/classworlds/classworlds/1.1/classworlds-1.1.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_110")
			.get("/nexus/content/groups/public/org/apache/maven/shared/maven-filtering/1.0-beta-4/maven-filtering-1.0-beta-4.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_111")
			.get("/nexus/content/groups/public/org/apache/maven/shared/maven-filtering/1.0-beta-4/maven-filtering-1.0-beta-4.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_112")
			.get("/nexus/content/groups/public/org/apache/maven/shared/maven-shared-components/15/maven-shared-components-15.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_113")
			.get("/nexus/content/groups/public/org/apache/maven/shared/maven-shared-components/15/maven-shared-components-15.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_114")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_115")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/1.5.15/plexus-utils-1.5.15.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_116")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/2.0.2/plexus-2.0.2.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_117")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/2.0.2/plexus-2.0.2.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_118")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-interpolation/1.12/plexus-interpolation-1.12.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_119")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-interpolation/1.12/plexus-interpolation-1.12.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_120")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-components/1.1.14/plexus-components-1.1.14.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_121")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-components/1.1.14/plexus-components-1.1.14.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_122")
			.get("/nexus/content/groups/public/org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_123")
			.get("/nexus/content/groups/public/org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_124")
			.get("/nexus/content/groups/public/org/sonatype/spice/spice-parent/10/spice-parent-10.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_125")
			.get("/nexus/content/groups/public/org/sonatype/spice/spice-parent/10/spice-parent-10.pom.sha1")
			.headers(headers_44)
		)
		.pause(100, 200, MILLISECONDS)
		.exec(
			http("request_126")
			.get("/nexus/content/groups/public/org/sonatype/forge/forge-parent/3/forge-parent-3.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_127")
			.get("/nexus/content/groups/public/org/sonatype/forge/forge-parent/3/forge-parent-3.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_128")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_129")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_130")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_131")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_132")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-components/1.1.15/plexus-components-1.1.15.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_133")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-components/1.1.15/plexus-components-1.1.15.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_134")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/2.0.3/plexus-2.0.3.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_135")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/2.0.3/plexus-2.0.3.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_136")
			.get("/nexus/content/groups/public/org/apache/maven/reporting/maven-reporting-api/2.0.6/maven-reporting-api-2.0.6.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_137")
			.get("/nexus/content/groups/public/org/apache/maven/reporting/maven-reporting-api/2.0.6/maven-reporting-api-2.0.6.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_138")
			.get("/nexus/content/groups/public/org/apache/maven/shared/maven-filtering/1.0-beta-4/maven-filtering-1.0-beta-4.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_139")
			.get("/nexus/content/groups/public/org/apache/maven/shared/maven-filtering/1.0-beta-4/maven-filtering-1.0-beta-4.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_140")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_141")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_142")
			.get("/nexus/content/groups/public/commons-cli/commons-cli/1.0/commons-cli-1.0.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_143")
			.get("/nexus/content/groups/public/commons-cli/commons-cli/1.0/commons-cli-1.0.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_144")
			.get("/nexus/content/groups/public/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_145")
			.get("/nexus/content/groups/public/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_146")
			.get("/nexus/content/groups/public/org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_147")
			.get("/nexus/content/groups/public/org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_148")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_149")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-interpolation/1.13/plexus-interpolation-1.13.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_150")
			.get("/nexus/content/groups/public/org/apache/maven/maven-toolchain/1.0/maven-toolchain-1.0.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_151")
			.get("/nexus/content/groups/public/org/apache/maven/maven-toolchain/1.0/maven-toolchain-1.0.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_152")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler-api/1.8.1/plexus-compiler-api-1.8.1.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_153")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler-api/1.8.1/plexus-compiler-api-1.8.1.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_154")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler/1.8.1/plexus-compiler-1.8.1.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_155")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler/1.8.1/plexus-compiler-1.8.1.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_156")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-components/1.1.18/plexus-components-1.1.18.pom")
			.headers(headers_44)
		)
		
	val chain3 = chain.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_157")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-components/1.1.18/plexus-components-1.1.18.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_158")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/2.0.7/plexus-2.0.7.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_159")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/2.0.7/plexus-2.0.7.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_160")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/1.5.5/plexus-utils-1.5.5.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_161")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-utils/1.5.5/plexus-utils-1.5.5.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_162")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler-manager/1.8.1/plexus-compiler-manager-1.8.1.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_163")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler-manager/1.8.1/plexus-compiler-manager-1.8.1.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_164")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler-javac/1.8.1/plexus-compiler-javac-1.8.1.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_165")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler-javac/1.8.1/plexus-compiler-javac-1.8.1.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_166")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compilers/1.8.1/plexus-compilers-1.8.1.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_167")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compilers/1.8.1/plexus-compilers-1.8.1.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_168")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler-api/1.8.1/plexus-compiler-api-1.8.1.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_169")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler-api/1.8.1/plexus-compiler-api-1.8.1.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_170")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler-javac/1.8.1/plexus-compiler-javac-1.8.1.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_171")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler-javac/1.8.1/plexus-compiler-javac-1.8.1.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_172")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler-manager/1.8.1/plexus-compiler-manager-1.8.1.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_173")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-compiler-manager/1.8.1/plexus-compiler-manager-1.8.1.jar.sha1")
			.headers(headers_44)
		)
		.pause(300, 400, MILLISECONDS)
		.exec(
			http("request_174")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-api/2.0.9/maven-plugin-api-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_175")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-api/2.0.9/maven-plugin-api-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_176")
			.get("/nexus/content/groups/public/org/apache/maven/maven/2.0.9/maven-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_177")
			.get("/nexus/content/groups/public/org/apache/maven/maven/2.0.9/maven-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_178")
			.get("/nexus/content/groups/public/org/apache/maven/maven-parent/8/maven-parent-8.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_179")
			.get("/nexus/content/groups/public/org/apache/maven/maven-parent/8/maven-parent-8.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_180")
			.get("/nexus/content/groups/public/org/apache/apache/4/apache-4.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_181")
			.get("/nexus/content/groups/public/org/apache/apache/4/apache-4.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_182")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-booter/2.7.2/surefire-booter-2.7.2.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_183")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-booter/2.7.2/surefire-booter-2.7.2.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_184")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-api/2.7.2/surefire-api-2.7.2.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_185")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-api/2.7.2/surefire-api-2.7.2.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_186")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/maven-surefire-common/2.7.2/maven-surefire-common-2.7.2.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_187")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/maven-surefire-common/2.7.2/maven-surefire-common-2.7.2.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_188")
			.get("/nexus/content/groups/public/org/apache/maven/maven-artifact/2.0.9/maven-artifact-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_189")
			.get("/nexus/content/groups/public/org/apache/maven/maven-artifact/2.0.9/maven-artifact-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_190")
			.get("/nexus/content/groups/public/org/apache/maven/maven-project/2.0.9/maven-project-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_191")
			.get("/nexus/content/groups/public/org/apache/maven/maven-project/2.0.9/maven-project-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_192")
			.get("/nexus/content/groups/public/org/apache/maven/maven-settings/2.0.9/maven-settings-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_193")
			.get("/nexus/content/groups/public/org/apache/maven/maven-settings/2.0.9/maven-settings-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_194")
			.get("/nexus/content/groups/public/org/apache/maven/maven-model/2.0.9/maven-model-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_195")
			.get("/nexus/content/groups/public/org/apache/maven/maven-model/2.0.9/maven-model-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_196")
			.get("/nexus/content/groups/public/org/apache/maven/maven-profile/2.0.9/maven-profile-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_197")
			.get("/nexus/content/groups/public/org/apache/maven/maven-profile/2.0.9/maven-profile-2.0.9.pom.sha1")
			.headers(headers_44)
		)
	
	val chain4 = chain
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_198")
			.get("/nexus/content/groups/public/org/apache/maven/maven-artifact-manager/2.0.9/maven-artifact-manager-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_199")
			.get("/nexus/content/groups/public/org/apache/maven/maven-artifact-manager/2.0.9/maven-artifact-manager-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_200")
			.get("/nexus/content/groups/public/org/apache/maven/maven-repository-metadata/2.0.9/maven-repository-metadata-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_201")
			.get("/nexus/content/groups/public/org/apache/maven/maven-repository-metadata/2.0.9/maven-repository-metadata-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_202")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-registry/2.0.9/maven-plugin-registry-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_203")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-registry/2.0.9/maven-plugin-registry-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_204")
			.get("/nexus/content/groups/public/org/apache/maven/maven-core/2.0.9/maven-core-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_205")
			.get("/nexus/content/groups/public/org/apache/maven/maven-core/2.0.9/maven-core-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_206")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-parameter-documenter/2.0.9/maven-plugin-parameter-documenter-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_207")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-parameter-documenter/2.0.9/maven-plugin-parameter-documenter-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_208")
			.get("/nexus/content/groups/public/org/apache/maven/reporting/maven-reporting-api/2.0.9/maven-reporting-api-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_209")
			.get("/nexus/content/groups/public/org/apache/maven/reporting/maven-reporting-api/2.0.9/maven-reporting-api-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_210")
			.get("/nexus/content/groups/public/org/apache/maven/reporting/maven-reporting/2.0.9/maven-reporting-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_211")
			.get("/nexus/content/groups/public/org/apache/maven/reporting/maven-reporting/2.0.9/maven-reporting-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_212")
			.get("/nexus/content/groups/public/org/apache/maven/maven-error-diagnostics/2.0.9/maven-error-diagnostics-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_213")
			.get("/nexus/content/groups/public/org/apache/maven/maven-error-diagnostics/2.0.9/maven-error-diagnostics-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_214")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-descriptor/2.0.9/maven-plugin-descriptor-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_215")
			.get("/nexus/content/groups/public/org/apache/maven/maven-plugin-descriptor/2.0.9/maven-plugin-descriptor-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_216")
			.get("/nexus/content/groups/public/org/apache/maven/maven-monitor/2.0.9/maven-monitor-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_217")
			.get("/nexus/content/groups/public/org/apache/maven/maven-monitor/2.0.9/maven-monitor-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_218")
			.get("/nexus/content/groups/public/org/apache/maven/maven-toolchain/2.0.9/maven-toolchain-2.0.9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_219")
			.get("/nexus/content/groups/public/org/apache/maven/maven-toolchain/2.0.9/maven-toolchain-2.0.9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_220")
			.get("/nexus/content/groups/public/org/apache/maven/shared/maven-common-artifact-filters/1.3/maven-common-artifact-filters-1.3.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_221")
			.get("/nexus/content/groups/public/org/apache/maven/shared/maven-common-artifact-filters/1.3/maven-common-artifact-filters-1.3.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_222")
			.get("/nexus/content/groups/public/org/apache/maven/shared/maven-shared-components/12/maven-shared-components-12.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_223")
			.get("/nexus/content/groups/public/org/apache/maven/shared/maven-shared-components/12/maven-shared-components-12.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_224")
			.get("/nexus/content/groups/public/org/apache/maven/maven-parent/13/maven-parent-13.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_225")
			.get("/nexus/content/groups/public/org/apache/maven/maven-parent/13/maven-parent-13.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_226")
			.get("/nexus/content/groups/public/org/apache/apache/6/apache-6.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_227")
			.get("/nexus/content/groups/public/org/apache/apache/6/apache-6.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_228")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-container-default/1.0-alpha-9/plexus-container-default-1.0-alpha-9.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_229")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-container-default/1.0-alpha-9/plexus-container-default-1.0-alpha-9.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_230")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/maven-surefire-common/2.7.2/maven-surefire-common-2.7.2.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_231")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/maven-surefire-common/2.7.2/maven-surefire-common-2.7.2.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_232")
			.get("/nexus/content/groups/public/org/apache/maven/shared/maven-common-artifact-filters/1.3/maven-common-artifact-filters-1.3.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_233")
			.get("/nexus/content/groups/public/org/apache/maven/shared/maven-common-artifact-filters/1.3/maven-common-artifact-filters-1.3.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_234")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-booter/2.7.2/surefire-booter-2.7.2.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_235")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-booter/2.7.2/surefire-booter-2.7.2.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_236")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-api/2.7.2/surefire-api-2.7.2.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_237")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-api/2.7.2/surefire-api-2.7.2.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_238")
			.get("/nexus/content/groups/public/org/apache/maven/reporting/maven-reporting-api/2.0.9/maven-reporting-api-2.0.9.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_239")
			.get("/nexus/content/groups/public/org/apache/maven/reporting/maven-reporting-api/2.0.9/maven-reporting-api-2.0.9.jar.sha1")
			.headers(headers_44)
		)
		.pause(100, 200, MILLISECONDS)
		.exec(
			http("request_240")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-junit3/2.7.2/surefire-junit3-2.7.2.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_241")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-junit3/2.7.2/surefire-junit3-2.7.2.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_242")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-providers/2.7.2/surefire-providers-2.7.2.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_243")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-providers/2.7.2/surefire-providers-2.7.2.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_244")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-junit3/2.7.2/surefire-junit3-2.7.2.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_245")
			.get("/nexus/content/groups/public/org/apache/maven/surefire/surefire-junit3/2.7.2/surefire-junit3-2.7.2.jar.sha1")
			.headers(headers_44)
		)
		.pause(700, 800, MILLISECONDS)
		.exec(
			http("request_246")
			.get("/nexus/content/groups/public/org/apache/maven/maven-archiver/2.4.1/maven-archiver-2.4.1.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_247")
			.get("/nexus/content/groups/public/org/apache/maven/maven-archiver/2.4.1/maven-archiver-2.4.1.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_248")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-archiver/1.0/plexus-archiver-1.0.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_249")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-archiver/1.0/plexus-archiver-1.0.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_250")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-components/1.1.17/plexus-components-1.1.17.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_251")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-components/1.1.17/plexus-components-1.1.17.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_252")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/2.0.5/plexus-2.0.5.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_253")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/2.0.5/plexus-2.0.5.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_254")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-io/1.0/plexus-io-1.0.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_255")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-io/1.0/plexus-io-1.0.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_256")
			.get("/nexus/content/groups/public/commons-lang/commons-lang/2.1/commons-lang-2.1.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_257")
			.get("/nexus/content/groups/public/commons-lang/commons-lang/2.1/commons-lang-2.1.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_258")
			.get("/nexus/content/groups/public/org/apache/maven/maven-archiver/2.4.1/maven-archiver-2.4.1.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_259")
			.get("/nexus/content/groups/public/org/apache/maven/maven-archiver/2.4.1/maven-archiver-2.4.1.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_260")
			.get("/nexus/content/groups/public/commons-lang/commons-lang/2.1/commons-lang-2.1.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_261")
			.get("/nexus/content/groups/public/commons-lang/commons-lang/2.1/commons-lang-2.1.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_262")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-io/1.0/plexus-io-1.0.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_263")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-io/1.0/plexus-io-1.0.jar.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_264")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-archiver/1.0/plexus-archiver-1.0.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_265")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-archiver/1.0/plexus-archiver-1.0.jar.sha1")
			.headers(headers_44)
		)
		.pause(300, 400, MILLISECONDS)
		.exec(
			http("request_266")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_267")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_268")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-components/1.1.7/plexus-components-1.1.7.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_269")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-components/1.1.7/plexus-components-1.1.7.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_270")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/1.0.8/plexus-1.0.8.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_271")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus/1.0.8/plexus-1.0.8.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_272")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-container-default/1.0-alpha-8/plexus-container-default-1.0-alpha-8.pom")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_273")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-container-default/1.0-alpha-8/plexus-container-default-1.0-alpha-8.pom.sha1")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_274")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.jar")
			.headers(headers_44)
		)
		.pause(0, 100, MILLISECONDS)
		.exec(
			http("request_275")
			.get("/nexus/content/groups/public/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.jar.sha1")
			.headers(headers_44)
		)

	val scn = scenario("Scenario name").insertChain(chain1).insertChain(chain2).insertChain(chain3).insertChain(chain4)

	runSimulation(
		scn.configure users 1 protocolConfig httpConf
	)
	
}