addSbtPlugin("io.gatling"         % "gatling-build-plugin"  % "4.0.1")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager"   % "1.8.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"               % "0.4.3")
addSbtPlugin("net.aichler"        % "sbt-jupiter-interface" % "0.9.1")
addSbtPlugin("com.typesafe.sbt"   % "sbt-site"              % "1.4.1")
addSbtPlugin("org.wartremover"    % "sbt-wartremover"       % "2.4.16")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"          % "0.9.31")
addSbtPlugin("net.moznion.sbt"    % "sbt-spotless"          % "0.1.3")
