package com.excilys.ebi.gatling.http.request

object RequestHeader {
  val AcceptRanges = "Accept-Ranges"
  val Age = "Age"
  val Allow = "Allow"
  val CacheControl = "Cache-Control"
  val Connection = "Connection"
  val ContentEncoding = "Content-Encoding"
  val ContentLanguage = "Content-Language"
  val ContentLength = "Content-Length"
  val ContentLocation = "Content-Location"
  val ContentMD5 = "Content-MD5"
  val ContentDisposition = "Content-Disposition"
  val ContentRange = "Content-Range"
  val ContentType = "Content-Type"
  val Date = "Date"
  val ETag = "ETag"
  val Expires = "Expires"
  val LastModified = "Last-Modified"
  val Link = "Link"
  val Location = "Location"
  val P3P = "P3P"
  val Pragma = "Pragma"
  val ProxyAuthenticate = "Proxy-Authenticate"
  val Refresh = "Refresh"
  val RetryAfter = "Retry-After"
  val Server = "Server"
  val SetCookie = "Set-Cookie"
  val StrictTransportSecurity = "Strict-Transport-Security"
  val Trailer = "Trailer"
  val TransferEncoding = "Transfer-Encoding"
  val Vary = "Vary"
  val Via = "Via"
  val Warning = "Warning"
  val WWWAuthenticate = "WWW-Authenticate"
}