name: build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      JAVA_OPTS: "-Xmx6G"
      SBT_OPTS: "-Dsbt.ci=true -Xss100M"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup JDK
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Setup sbt
        uses: sbt/setup-sbt@c7d2d6258b4bd0d3ec5129e6b3453199d3c79729 # v1.5.8

      - name: Cache SBT
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.m2/repository
            ~/.ivy2/cache
            ~/.cache/coursier
            ~/.sbt/launchers
            ~/.sbt/boot
            ~/.sbt/preloaded
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/plugins.sbt', '**/build.properties') }}

      - name: Test
        run: |
          sbt \
            "headerCheckAll" \
            "scalafmtSbtCheck" \
            "scalafmtCheckAll" \
            "javafmtCheckAll" \
            "scalafixAll --check" \
            "test"
